#!/bin/bash
#
#SBATCH --partition=long
#SBATCH --job-name=microSLURM_shotgun
#SBATCH --output=microSLURM_shotgun.log
#SBATCH --ntasks=1
#SBATCH --time=150:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Load R module
module load R

#Provide location for directory containing raw input sequences, and directory to place pipeline output
SEQ_DIR=
OUT_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/microSLURM_shotgun.sh \
-i ${SEQ_DIR} \
-o ${OUT_DIR} \
-p 'conda activate microSLURM_shotgun' \
-r ${PIPELINE_DIR}/Reference_Files/GCA_000001405.28_GRCh38.p13_genomic.fna \
-c ${PIPELINE_DIR}/Reference_Files/full_chocophlan.v296_201901b \
-u ${PIPELINE_DIR}/Reference_Files/uniref90_annotated_v201901b_full \
#-b ${PIPELINE_DIR}/Reference_Files_Databases/k2_standard_20220926 \ <-- uncomment if wanting to use Kraken2/Bracken for taxonomic profiling instead of MetaPhlAn
-n express,NA,short,short,short,express,short,medium \
-t 2:00:00,NA,12:00:00,12:00:00,12:00:00,2:00:00,12:00:00,50:00:00 \
-k 1,NA,1,10,1,1,10,10 \
-m 12000,NA,12000,12000,12000,12000,16000,16000 \
-f user@institution.edu \
-d
