#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Initial_FastQC
#SBATCH --error=Initial_FastQC.err
#SBATCH --output=Initial_FastQC.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of directory containing sequences and pipeline output directory
SEQ_DIR=
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/1.Initial_FastQC.sh \
-i $SEQ_DIR \
-o $RESULTS_DIR \
-p 'conda activate shotgun_pipeline' \
-n express \
-t 2:00:00 \
-k 1 \
-m 12000 \
-f user@institution.edu
