#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Merge_PE_Reads
#SBATCH --error=Merge_PE_Reads.err
#SBATCH --output=Merge_PE_Reads.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/2.Merge_PE_Reads.sh \
-o $RESULTS_DIR \
-s
