#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Low_Complexity_Sequence_Filtering
#SBATCH --error=Low_Complexity_Sequence_Filtering.err
#SBATCH --output=Low_Complexity_Sequence_Filtering.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/5.Low_Complexity_Sequence_Filtering.sh \
-o $RESULTS_DIR \
-p 'conda activate shotgun_pipeline' \
-n short \
-t 12:00:00 \
-k 1 \
-m 12000 \
-f user@institution.edu
