#!/bin/bash
#
#SBATCH --partition=express
#SBATCH --job-name=Delete_Intermediate_Sequence_Files
#SBATCH --error=Delete_Intermediate_Sequence_Files.err
#SBATCH --output=Delete_Intermediate_Sequence_Files.out
#SBATCH --ntasks=1
#SBATCH --time=2:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of directory containing sequences that were processed and pipeline output directory
SEQ_DIR=
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/Delete_Intermediate_Sequence_Files.sh \
-i $SEQ_DIR \
-o $RESULTS_DIR \
-n express \
-t 2:00:00 \
-k 1 \
-m 4000 \
-f user@institution.edu
