#!/bin/bash
#
#SBATCH --partition=express
#SBATCH --job-name=Pipeline_Report
#SBATCH --error=Pipeline_Report.err
#SBATCH --output=Pipeline_Report.out
#SBATCH --ntasks=1
#SBATCH --time=2:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/Pipeline_Report.sh \
-o $RESULTS_DIR \
-p 'conda activate shotgun_pipeline' \
-n express \
-t 2:00:00 \
-k 1 \
-m 4000 \
-f user@institution.edu
