#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Final_FastQC
#SBATCH --error=Final_FastQC.err
#SBATCH --output=Final_FastQC.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/6.Final_FastQC.sh \
-o $RESULTS_DIR \
-p 'conda activate shotgun_pipeline' \
-n express \
-t 2:00:00 \
-k 1 \
-m 12000 \
-f user@institution.edu
