#!/bin/bash
#
#SBATCH --partition=short
#SBATCH --job-name=Taxonomic_Profiling
#SBATCH --error=Taxonomic_Profiling.err
#SBATCH --output=Taxonomic_Profiling.out
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4000
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=user@institution.edu

#Provide location of pipeline output directory
RESULTS_DIR=

#Provide location of pipeline directory
PIPELINE_DIR=

#Launch pipeline script
${PIPELINE_DIR}/SLURM_Shotgun_Metagenomic_Pipeline/7.Taxonomic_Profiling.sh \
-o $RESULTS_DIR \
-p 'conda activate shotgun_pipeline' \
#-b ${PIPELINE_DIR}/Reference_Files_Databases/k2_standard_20220926 \ <-- uncomment if wanting to use Kraken2/Bracken for taxonomic profiling instead of MetaPhlAn
-n short \
-t 12:00:00 \
-k 10 \
-m 16000 \
-f user@institution.edu
